"""Fermionic mode indexing from arbitrary discrete degrees of freedom."""

from __future__ import annotations

from .._core._modes import DoF, DiscreteModes


class FermionModes(DiscreteModes):
    """Ordered fermionic modes generated by discrete degrees of freedom.

    Parameters
    ----------
    *dofs : DoF
        Degrees of freedom whose Cartesian product labels the fermionic
        modes. The first degree of freedom is the fastest-varying index.

    Notes
    -----
    For degrees of freedom with sizes ``(N0, N1, ...)``, the tuple
    ``(i0, i1, ...)`` is mapped to a single fermionic mode using shared
    mixed-radix indexing. No single-particle wavefunctions are constructed or
    stored.
    """

    __slots__ = ()
