"""Fermionic mode indexing from arbitrary discrete degrees of freedom."""

from __future__ import annotations

from dataclasses import dataclass
from math import prod
from numbers import Integral


@dataclass(frozen=True, slots=True)
class DoF:
    """Discrete degree of freedom used to label fermionic modes.

    Parameters
    ----------
    size : int
        Number of allowed values of the degree of freedom.
    name : str, optional
        Descriptive name, such as ``"site"``, ``"spin"``, ``"orbital"``,
        ``"layer"``, or ``"valley"``.

    Notes
    -----
    ``DoF`` is only a discrete label specification. It does not represent a
    quantum state or a Hilbert space by itself.
    """

    size: int
    name: str | None = None

    def __post_init__(self):
        """Validate the degree-of-freedom cardinality and optional name."""
        if not isinstance(self.size, Integral):
            raise TypeError("'size' must be an integer.")
        if self.size <= 0:
            raise ValueError("'size' must be positive.")
        if self.name is not None and not isinstance(self.name, str):
            raise TypeError("'name' must be a string or None.")
        object.__setattr__(self, "size", int(self.size))


class FermionModes:
    """Ordered fermionic modes generated by discrete degrees of freedom.

    Parameters
    ----------
    *dofs : DoF
        Degrees of freedom whose Cartesian product labels the fermionic
        modes. The first degree of freedom is the fastest-varying index.

    Notes
    -----
    For degrees of freedom with sizes ``(N0, N1, ...)``, the tuple
    ``(i0, i1, ...)`` is mapped to a single fermionic mode using mixed-radix
    indexing. No single-particle wavefunctions are constructed or stored.
    """

    __slots__ = ("_dofs", "_strides", "_n_modes")

    def __init__(self, *dofs: DoF):
        """Construct the ordered fermionic-mode set."""
        if not dofs:
            raise ValueError("At least one DoF is required.")
        if not all(isinstance(dof, DoF) for dof in dofs):
            raise TypeError("All arguments must be DoF instances.")

        strides = []
        stride = 1
        for dof in dofs:
            strides.append(stride)
            stride *= dof.size

        self._dofs = tuple(dofs)
        self._strides = tuple(strides)
        self._n_modes = prod(dof.size for dof in dofs)

    def __len__(self):
        """Return the number of fermionic modes."""
        return self._n_modes

    def __repr__(self):
        """Return an unambiguous representation of the mode specification."""
        args = ", ".join(repr(dof) for dof in self._dofs)
        return f"FermionModes({args})"

    @property
    def dofs(self):
        """tuple[DoF, ...]: Degrees of freedom defining the modes."""
        return self._dofs

    @property
    def strides(self):
        """tuple[int, ...]: Mixed-radix strides for the degree-of-freedom indices."""
        return self._strides

    @property
    def n_modes(self):
        """int: Total number of fermionic modes."""
        return self._n_modes

    def resolve(self, indices):
        """Map degree-of-freedom indices to a fermionic-mode index.

        Parameters
        ----------
        indices : tuple of int or int
            Degree-of-freedom indices. A bare integer is accepted only when
            exactly one degree of freedom is present.

        Returns
        -------
        int
            Zero-based fermionic-mode index.
        """
        if isinstance(indices, Integral):
            if len(self._dofs) != 1:
                raise ValueError(
                    f"Expected {len(self._dofs)} indices, received one."
                )
            indices = (int(indices),)
        else:
            indices = tuple(indices)

        if len(indices) != len(self._dofs):
            raise ValueError(
                f"Expected {len(self._dofs)} indices, received {len(indices)}."
            )

        mode = 0
        for index, dof, stride in zip(indices, self._dofs, self._strides):
            if not isinstance(index, Integral):
                raise TypeError("Mode indices must be integers.")
            index = int(index)
            if index < 0 or index >= dof.size:
                label = dof.name or "unnamed DoF"
                raise IndexError(
                    f"Index {index} is outside [0, {dof.size}) for {label}."
                )
            mode += index * stride
        return mode

    def unravel(self, mode):
        """Map a fermionic-mode index back to degree-of-freedom indices.

        Parameters
        ----------
        mode : int
            Zero-based fermionic-mode index.

        Returns
        -------
        tuple[int, ...]
            Degree-of-freedom indices in the order supplied at construction.
        """
        if not isinstance(mode, Integral):
            raise TypeError("'mode' must be an integer.")
        mode = int(mode)
        if mode < 0 or mode >= self._n_modes:
            raise IndexError(
                f"Mode index {mode} is outside [0, {self._n_modes})."
            )

        return tuple(
            (mode // stride) % dof.size
            for dof, stride in zip(self._dofs, self._strides)
        )
