import numpy as np

from edinpy import fermion as edf


# ---------------------------------------------------------------------------
# Independent reference implementation
# ---------------------------------------------------------------------------

def fermionic_sign(state, mode):
    """Fock-ordering sign for acting on `mode`."""
    mask = (1 << mode) - 1
    return -1 if (state & mask).bit_count() & 1 else 1


def annihilate(state, mode):
    """Independent reference action of c_mode."""
    if not state & (1 << mode):
        return None

    sign = fermionic_sign(state, mode)
    return state ^ (1 << mode), sign


def create(state, mode):
    """Independent reference action of c_mode^dagger."""
    if state & (1 << mode):
        return None

    sign = fermionic_sign(state, mode)
    return state ^ (1 << mode), sign


def hop(state, destination, source):
    """Independent reference action of c_destination^dagger c_source."""
    result = annihilate(state, source)
    if result is None:
        return None

    intermediate, sign_a = result

    result = create(intermediate, destination)
    if result is None:
        return None

    final, sign_c = result
    return final, sign_a * sign_c


def make_model(neff, nf):
    edf.clear()
    edf.DoF(neff, name="orbital")
    return edf.model(nf)


# ---------------------------------------------------------------------------
# One-particle hopping
# ---------------------------------------------------------------------------

def test_two_mode_hopping_matrix():
    t = 1.7

    model = make_model(neff=2, nf=1)

    c0 = edf.operator(0)
    c1 = edf.operator(1)

    op = -t * (
        c0.dag * c1
        + c1.dag * c0
    )

    H = edf.hamiltonian(op).array

    expected = np.array(
        [
            [0.0, -t],
            [-t, 0.0],
        ],
        dtype=complex,
    )

    assert model.fockspace.ls == [1, 2]
    np.testing.assert_allclose(H, expected, atol=1e-6)


def test_two_mode_hopping_spectrum():
    t = 1.7

    make_model(neff=2, nf=1)

    c0 = edf.operator(0)
    c1 = edf.operator(1)

    op = -t * (
        c0.dag * c1
        + c1.dag * c0
    )

    eigvals = np.linalg.eigvalsh(edf.hamiltonian(op).array)

    np.testing.assert_allclose(
        eigvals,
        [-t, t],
        atol=1e-6,
    )


def test_complex_hopping_phase():
    """
    Test

        H = a c_0^dagger c_1 + a* c_1^dagger c_0

    for a genuinely complex hopping amplitude.
    """
    amp = 0.7 + 1.2j

    make_model(neff=2, nf=1)

    c0 = edf.operator(0)
    c1 = edf.operator(1)

    op = (
        amp * (c0.dag * c1)
        + amp.conjugate() * (c1.dag * c0)
    )

    H = edf.hamiltonian(op).array

    expected = np.array(
        [
            [0.0, amp],
            [amp.conjugate(), 0.0],
        ],
        dtype=complex,
    )

    np.testing.assert_allclose(H, expected, atol=1e-6)
    np.testing.assert_allclose(H, H.conjugate().T, atol=1e-6)


# ---------------------------------------------------------------------------
# Density interactions
# ---------------------------------------------------------------------------

def test_density_density_matrix():
    V = 2.3

    model = make_model(neff=3, nf=2)

    n0 = edf.number(0)
    n1 = edf.number(1)

    H = edf.hamiltonian(V * n0 * n1).array

    # Basis:
    #   3 = 011 -> modes 0,1 occupied
    #   5 = 101 -> modes 0,2 occupied
    #   6 = 110 -> modes 1,2 occupied
    assert model.fockspace.ls == [3, 5, 6]

    expected = np.diag([V, 0.0, 0.0])

    np.testing.assert_allclose(H, expected, atol=1e-6)


# ---------------------------------------------------------------------------
# Two-site spinful Hubbard model
# ---------------------------------------------------------------------------

def build_two_site_hubbard(t, U):
    """
    Effective-mode ordering generated by EDinPy:

        mode 0 = (site 0, spin 0)
        mode 1 = (site 1, spin 0)
        mode 2 = (site 0, spin 1)
        mode 3 = (site 1, spin 1)
    """
    edf.clear()

    edf.DoF(2, name="site")
    edf.DoF(2, name="spin")

    model = edf.model(2)

    c00 = edf.operator([0, 0])
    c10 = edf.operator([1, 0])
    c01 = edf.operator([0, 1])
    c11 = edf.operator([1, 1])

    hopping = -t * (
        c00.dag * c10
        + c10.dag * c00
        + c01.dag * c11
        + c11.dag * c01
    )

    interaction = U * (
        edf.number([0, 0]) * edf.number([0, 1])
        + edf.number([1, 0]) * edf.number([1, 1])
    )

    return model, edf.hamiltonian(hopping + interaction)


def reference_two_site_hubbard(model, t, U):
    """
    Construct the same Hamiltonian independently using integer Fock states,
    bit operations, and the canonical fermionic sign.
    """
    basis = model.fockspace.ls
    index = {state: i for i, state in enumerate(basis)}

    H = np.zeros((len(basis), len(basis)), dtype=complex)

    # mode = site + 2 * spin
    for col, state in enumerate(basis):

        # Hopping for each spin.
        for spin in (0, 1):
            mode0 = 0 + 2 * spin
            mode1 = 1 + 2 * spin

            for destination, source in (
                (mode0, mode1),
                (mode1, mode0),
            ):
                result = hop(state, destination, source)

                if result is not None:
                    new_state, sign = result
                    row = index[new_state]
                    H[row, col] += -t * sign

        # On-site Hubbard interaction.
        for site in (0, 1):
            up = site
            down = site + 2

            if (
                state & (1 << up)
                and state & (1 << down)
            ):
                H[col, col] += U

    return H


def test_two_site_hubbard_matrix_matches_independent_reference():
    t = 1.3
    U = 4.2

    model, hamiltonian = build_two_site_hubbard(t=t, U=U)

    calculated = hamiltonian.array
    expected = reference_two_site_hubbard(model, t=t, U=U)

    assert model.fockspace.ls == [3, 5, 6, 9, 10, 12]

    np.testing.assert_allclose(
        calculated,
        expected,
        atol=1e-6,
    )

    np.testing.assert_allclose(
        calculated,
        calculated.conjugate().T,
        atol=1e-6,
    )


def test_two_site_hubbard_analytic_spectrum():
    """
    Half-filled two-site Hubbard model:

        E = (U - sqrt(U^2 + 16 t^2))/2
        E = 0                        (triplet, threefold)
        E = U
        E = (U + sqrt(U^2 + 16 t^2))/2
    """
    t = 1.3
    U = 4.2

    _, hamiltonian = build_two_site_hubbard(t=t, U=U)

    eigvals = np.linalg.eigvalsh(hamiltonian.array)

    root = np.sqrt(U**2 + 16.0 * t**2)

    expected = np.array(
        [
            0.5 * (U - root),
            0.0,
            0.0,
            0.0,
            U,
            0.5 * (U + root),
        ]
    )

    np.testing.assert_allclose(
        np.sort(eigvals),
        np.sort(expected),
        atol=1e-6,
    )


# ---------------------------------------------------------------------------
# Solver API
# ---------------------------------------------------------------------------

def test_dense_eigsolve_returns_requested_eigenpairs():
    """
    Verify the public dense eigensolver path, not merely NumPy applied
    externally to H.array.
    """
    t = 1.3
    U = 4.2

    _, hamiltonian = build_two_site_hubbard(t=t, U=U)

    hamiltonian.eigsolve(
        sparse=False,
        numeigs=2,
    )

    assert hamiltonian.eigvals.shape == (2,)
    assert hamiltonian.eigvecs.shape == (6, 2)

    reference = np.linalg.eigvalsh(hamiltonian.array)[:2]

    np.testing.assert_allclose(
        hamiltonian.eigvals,
        reference,
        atol=1e-6,
    )


def test_sparse_eigsolve_matches_dense_reference():
    t = 1.3
    U = 4.2

    _, hamiltonian = build_two_site_hubbard(t=t, U=U)

    reference = np.linalg.eigvalsh(hamiltonian.array)[:2]

    hamiltonian.eigsolve(
        sparse=True,
        numeigs=2,
        which="SA",
    )

    assert hamiltonian.eigvals.shape == (2,)
    assert hamiltonian.eigvecs.shape == (6, 2)

    np.testing.assert_allclose(
        np.sort(hamiltonian.eigvals),
        np.sort(reference),
        atol=1e-6,
    )


def test_nonhermitian_operator_matrix_is_preserved():
    """
    Matrix construction must represent the supplied operator directly rather
    than imposing Hermiticity.

    For basis [|10>, |01>] in EDinPy integer ordering,

        c_0^dagger c_1

    has only one nonzero matrix element.
    """
    make_model(neff=2, nf=1)

    c0 = edf.operator(0)
    c1 = edf.operator(1)

    H = edf.hamiltonian(c0.dag * c1).array

    expected = np.array(
        [
            [0.0, 1.0],
            [0.0, 0.0],
        ],
        dtype=complex,
    )

    np.testing.assert_allclose(H, expected, atol=1e-6)


def test_lowering_recognizes_number_and_hopping_terms():
    from edinpy.fermion._execution import compile_operator

    make_model(neff=4, nf=2)

    c0 = edf.Annihilation(0)
    c1 = edf.Annihilation(1)

    expression = (
        2.0 * edf.Number(0) * edf.Number(1)
        + 3.0 * c0.dag * c1
        + 3.0 * c1.dag * c0
    )

    compiled = compile_operator(expression)

    assert compiled.stats == {
        "number_product": 1,
        "hopping": 2,
        "generic": 0,
    }


def test_lowering_retains_generic_four_fermion_fallback():
    """
    A genuine four-fermion transition is intentionally not specialized yet.
    Verify that lowering falls back to the original Fock algebra correctly.
    """
    from edinpy.fermion._execution import compile_operator

    model = make_model(neff=4, nf=2)

    c0 = edf.Annihilation(0)
    c1 = edf.Annihilation(1)
    c2 = edf.Annihilation(2)
    c3 = edf.Annihilation(3)

    term = c0.dag * c1.dag * c3 * c2

    compiled = compile_operator(term)

    assert compiled.stats == {
        "number_product": 0,
        "hopping": 0,
        "generic": 1,
    }

    H = edf.hamiltonian(term).array

    # Build the expected matrix independently.
    expected = np.zeros_like(H, dtype=complex)
    basis = model.fockspace.ls
    index = {state: i for i, state in enumerate(basis)}

    for col, state in enumerate(basis):
        amplitude = 1
        current = state

        for kind, site in (
            ("annihilate", 2),
            ("annihilate", 3),
            ("create", 1),
            ("create", 0),
        ):
            if kind == "annihilate":
                result = annihilate(current, site)
            else:
                result = create(current, site)

            if result is None:
                amplitude = 0
                break

            current, sign = result
            amplitude *= sign

        if amplitude and current in index:
            expected[index[current], col] += amplitude

    np.testing.assert_allclose(H, expected, atol=1e-6)


def test_lowered_hopping_matches_independent_reference_exhaustively():
    """
    Verify direct lowered c_i^dagger c_j kernels for every pair of modes
    and every occupation state of a four-mode local Fock space.
    """
    from edinpy.fermion._execution import compile_operator

    neff = 4
    make_model(neff=neff, nf=2)

    for destination in range(neff):
        for source in range(neff):
            term = (
                edf.Annihilation(destination).dag
                * edf.Annihilation(source)
            )

            compiled = compile_operator(term)

            for state in range(1 << neff):
                ket_state = (
                    edf.vacuum()
                    if state == 0
                    else edf.fockstate(state)
                )

                calculated = compiled.apply(ket_state)

                if destination == source:
                    if state & (1 << source):
                        expected = {state: 1.0}
                    else:
                        expected = {}
                else:
                    reference = hop(
                        state,
                        destination,
                        source,
                    )

                    if reference is None:
                        expected = {}
                    else:
                        final_state, sign = reference
                        expected = {final_state: sign}

                assert set(calculated) == set(expected)

                for final_state, amplitude in expected.items():
                    assert np.isclose(
                        calculated[final_state],
                        amplitude,
                    )
